appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: SJgqcd8lNITpCvVQ3N/BC3OJUmjkf2YMXox5n+kcFSBA2DJOST2p+q907F206/RG1pfR0OzV3lXsP2lL7tV/TSEIUgXD918lQ1yjmx7n+nbShOUNToaci2nnC/XTDxR1UZ2nW0X0NjUERWilGTStJ5hP54pux5PVSkjUy7WbK84F4KmHZUk8/qg1NRDUYsxdYoGZuZdsywksyFfF0aHmlfY10m9JeG/fwmLkoRDYMf7wRObz5mii6dGjrB/cQvk9XiwI2oh70w1ktD2eKeUD5y08ppQXTwHuCc76smM238c5Bbh6ZyeF1+5BwbUVuja6h+AlAiVTw+YvhMtcrSdWgYpthiCTWcpFTQQ/Qu/vKvLt1wkjuOygWROUIbN6n/mJMKdDTxt1LK9WwmC4Z3KRuwAEpb4d5vQD7Vddj/FcPXXnLgnHw/6w3pg8SlnfUSlwUp2yqA9ItioFfwQQYfPIH11C1cIB71d3NBLU+i1L5gfenPywemr7nCEHP5jBecK58tOJdBjOK4RbBmUSCgPWWheJb+uYjCIxl3Wz69iNKCnHOzNfly9i37HCVnDFZV5o073xYK93a0YC8N2hyqFpWACNNGEA11ox33cUMGjCZJcrLzcyCF9FYBc08TZA1WV4ajoe2zmlFSShS0g+4Otm1GaKS2L7sZRjiXO1Y6XOyAE=}
bot:
  automerge: true
